#!/usr/bin/env python

# This script checks whether the Internet Archive's Wayback Machine has
# recent captures of the URLs we are tracking in the Web Monitoring Database.
# It works by taking a random sample of pages from the DB and using the CDX API
# to check that each has been captured at least once in the last few days.

from datetime import datetime, timedelta
import random
import sentry_sdk
import sys
from web_monitoring import db, internetarchive


MAX_CAPTURE_AGE = timedelta(hours=72)
LINKS_TO_CHECK = 10

# Sentry automatically instantiates with the `SENTRY_DSN` environment variable.
# If not set, all its methods will operate conveniently as no-ops.
sentry_sdk.init()


def sample_monitored_urls(sample_size):
    """
    Get a random sample of `sample_size` URLs that are tracked in a Web
    Monitoring DB instance.

    Returns
    -------
    list of string
    """
    client = db.Client.from_env()
    page = client.list_pages(chunk=1, chunk_size=1)
    url_count = page['meta']['total_results']
    return (get_page_url(client, index)
            for index in random.sample(range(url_count), sample_size))


def get_page_url(client, index):
    return client.list_pages(chunk=index, chunk_size=1)['data'][0]['url']


def wayback_has_captures(url, from_date=None):
    """
    Determine whether the Wayback Machine has any recent captures of a URL.

    Parameters
    ----------
    url : string

    Returns
    -------
    list of JSON
    """
    try:
        wayback = internetarchive.WaybackClient()
        versions = wayback.list_versions(url, from_date=from_date)
        next(versions)
    except ValueError:
        return False
    else:
        return True


def output_results(statuses):
    """
    Output nicely formatted results.

    Parameters
    ----------
    statuses: sequence of tuple of (str, bool)
    """
    healthy_links = 0
    unhealthy_links = 0

    logs = []
    for (url, status) in statuses:
        if status:
            healthy_links += 1
            status_text = '✔︎    Found'
        else:
            unhealthy_links += 1
            status_text = '✘  Missing'

        message = f'{status_text}: {url}'
        print(message)
        logs.append(message)

    if healthy_links + unhealthy_links == 0:
        print('Failed to sampled any pages!')
        sentry_sdk.capture_message('Failed to sampled any pages!')
    else:
        message = f'\nFound: {healthy_links} healthy links and {unhealthy_links} unhealthy links.'
        print(message)
        if unhealthy_links > 0:
            log_string = '\n'.join(logs)
            sentry_sdk.capture_message(f'{message}\n{log_string}')


if __name__ == "__main__":
    try:
        print(f'Sampling {LINKS_TO_CHECK} pages from Web Monitoring API...')
        links = sample_monitored_urls(LINKS_TO_CHECK)
        from_date = datetime.now() - MAX_CAPTURE_AGE
        print(f'Checking for captures in Wayback Machine...')
        capture_statuses = ((url, wayback_has_captures(url, from_date))
                            for url in links)
        output_results(capture_statuses)
    except db.MissingCredentials as error:
        print(error, file=sys.stderr)
